/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.BarberShop.GUI.model;

import ec.edu.espe.BarberShop.GUI.model.NewCustomer;
import static javax.swing.JOptionPane.showMessageDialog;
import ec.edu.espe.BarberShop.GUI.model.NewEmployee;
import ec.edu.espe.BarberShop.GUI.model.ModifyCustomer;
import ec.edu.espe.BarberShop.GUI.model.ModifyEmployee;
import ec.edu.espe.BarberShop.GUI.model.FindCustomer;
import ec.edu.espe.BarberShop.GUI.model.FindEmployee;
/**
 *
 * @author Sebastian Zuniga
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainDesktop
     */
    public MainMenu() {
        initComponents();
        MainMenu.this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jmbMenu = new javax.swing.JMenuBar();
        jmbArchivos = new javax.swing.JMenu();
        jmbExit = new javax.swing.JMenuItem();
        jmbCustomer = new javax.swing.JMenu();
        jmbNewCustomer = new javax.swing.JMenuItem();
        jmbModifyCustomer = new javax.swing.JMenuItem();
        jmbSearchCustomer = new javax.swing.JMenuItem();
        Empleados = new javax.swing.JMenu();
        jmbNewEmployee = new javax.swing.JMenuItem();
        jmbModifyEmployee = new javax.swing.JMenuItem();
        jmbSearchEmployee = new javax.swing.JMenuItem();
        Inventario = new javax.swing.JMenu();
        jmbSearchInventory = new javax.swing.JMenuItem();
        jmbAddInventory = new javax.swing.JMenuItem();
        Servicios = new javax.swing.JMenu();
        jmbSearchService = new javax.swing.JMenuItem();
        jmbModifyService = new javax.swing.JMenuItem();
        Ubicación = new javax.swing.JMenu();
        jmbLookLocation = new javax.swing.JMenuItem();
        jmbModifyLocation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        jmbArchivos.setText("Archivos");

        jmbExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jmbExit.setText("Cerrar");
        jmbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbExitActionPerformed(evt);
            }
        });
        jmbArchivos.add(jmbExit);

        jmbMenu.add(jmbArchivos);

        jmbCustomer.setText("Clientes");
        jmbCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbCustomerActionPerformed(evt);
            }
        });

        jmbNewCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmbNewCustomer.setText("Nuevo Cliente");
        jmbNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbNewCustomerActionPerformed(evt);
            }
        });
        jmbCustomer.add(jmbNewCustomer);

        jmbModifyCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmbModifyCustomer.setText("Modificar Cliente");
        jmbModifyCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbModifyCustomerActionPerformed(evt);
            }
        });
        jmbCustomer.add(jmbModifyCustomer);

        jmbSearchCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmbSearchCustomer.setText("Buscar Cliente");
        jmbSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbSearchCustomerActionPerformed(evt);
            }
        });
        jmbCustomer.add(jmbSearchCustomer);

        jmbMenu.add(jmbCustomer);

        Empleados.setText("Empleados");

        jmbNewEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmbNewEmployee.setText("Nuevo Empleado");
        jmbNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbNewEmployeeActionPerformed(evt);
            }
        });
        Empleados.add(jmbNewEmployee);

        jmbModifyEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmbModifyEmployee.setText("Modificar Empleado");
        jmbModifyEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbModifyEmployeeActionPerformed(evt);
            }
        });
        Empleados.add(jmbModifyEmployee);

        jmbSearchEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmbSearchEmployee.setText("Buscar Empleado");
        jmbSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbSearchEmployeeActionPerformed(evt);
            }
        });
        Empleados.add(jmbSearchEmployee);

        jmbMenu.add(Empleados);

        Inventario.setText("Inventario");

        jmbSearchInventory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jmbSearchInventory.setText("Verificar inventario");
        Inventario.add(jmbSearchInventory);

        jmbAddInventory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jmbAddInventory.setText("Añadir inventario");
        Inventario.add(jmbAddInventory);

        jmbMenu.add(Inventario);

        Servicios.setText("Servicios");

        jmbSearchService.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jmbSearchService.setText("Verificar Servicio");
        Servicios.add(jmbSearchService);

        jmbModifyService.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jmbModifyService.setText("Añadir Servicio");
        Servicios.add(jmbModifyService);

        jmbMenu.add(Servicios);

        Ubicación.setText("Ubicación");

        jmbLookLocation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jmbLookLocation.setText("Verificar la ubicación");
        Ubicación.add(jmbLookLocation);

        jmbModifyLocation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmbModifyLocation.setText("Modificar la ubicación");
        Ubicación.add(jmbModifyLocation);

        jmbMenu.add(Ubicación);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmbCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbCustomerActionPerformed
        
    }//GEN-LAST:event_jmbCustomerActionPerformed

    private void jmbNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbNewCustomerActionPerformed
        NewCustomer newCustomer = new NewCustomer();
        Desktop.add(newCustomer);
        newCustomer.show();
    }//GEN-LAST:event_jmbNewCustomerActionPerformed

    private void jmbSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbSearchCustomerActionPerformed
       FindCustomer findCustomer = new FindCustomer();
       Desktop.add(findCustomer);
       findCustomer.show();
    }//GEN-LAST:event_jmbSearchCustomerActionPerformed

    private void jmbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbExitActionPerformed
        showMessageDialog(null,"Gracias por usar el programa");
        System.exit(0);
    }//GEN-LAST:event_jmbExitActionPerformed

    private void jmbNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbNewEmployeeActionPerformed
       NewEmployee newEmployee = new NewEmployee();
       Desktop.add(newEmployee);
       newEmployee.show();
    }//GEN-LAST:event_jmbNewEmployeeActionPerformed

    private void jmbModifyEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbModifyEmployeeActionPerformed
        ModifyEmployee modifyEmployee = new ModifyEmployee();
        Desktop.add(modifyEmployee);
        modifyEmployee.show();
    }//GEN-LAST:event_jmbModifyEmployeeActionPerformed

    private void jmbModifyCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbModifyCustomerActionPerformed
        ModifyCustomer modifyCustomer = new ModifyCustomer();
        Desktop.add(modifyCustomer);
        modifyCustomer.show();
    }//GEN-LAST:event_jmbModifyCustomerActionPerformed

    private void jmbSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbSearchEmployeeActionPerformed
       FindEmployee findEmployee = new FindEmployee();
       Desktop.add(findEmployee);
       findEmployee.show();
    }//GEN-LAST:event_jmbSearchEmployeeActionPerformed
 
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu Empleados;
    private javax.swing.JMenu Inventario;
    private javax.swing.JMenu Servicios;
    private javax.swing.JMenu Ubicación;
    private javax.swing.JMenuItem jmbAddInventory;
    private javax.swing.JMenu jmbArchivos;
    private javax.swing.JMenu jmbCustomer;
    private javax.swing.JMenuItem jmbExit;
    private javax.swing.JMenuItem jmbLookLocation;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmbModifyCustomer;
    private javax.swing.JMenuItem jmbModifyEmployee;
    private javax.swing.JMenuItem jmbModifyLocation;
    private javax.swing.JMenuItem jmbModifyService;
    private javax.swing.JMenuItem jmbNewCustomer;
    private javax.swing.JMenuItem jmbNewEmployee;
    private javax.swing.JMenuItem jmbSearchCustomer;
    private javax.swing.JMenuItem jmbSearchEmployee;
    private javax.swing.JMenuItem jmbSearchInventory;
    private javax.swing.JMenuItem jmbSearchService;
    // End of variables declaration//GEN-END:variables
}
